FILESEXTRAPATHS_prepend := "${THISDIR}/linux-mainline:"

# These patches were fetched from the lovely guys at armbian: https://github.com/armbian/build/tree/sunxi-5.5/patch/kernel/sunxi-current

SRC_URI_append = " \
	file://armbian/0001-arm64-allwinner-a64-enable-Wi-Fi-for-Pine64.patch \
	file://armbian/0001-arm64-pine64-plus-add-PHY-regulator-delay.patch \
	file://armbian/0001-general-armbian-boot-logo.patch \
	file://armbian/0001-move_ANA78xx_driver_to_analogix_subdirectory.patch \
	file://armbian/0001-pinctrl-sunxi-Disable-strict-mode-for-A64-pinctrl-dr.patch \
	file://armbian/0002-split_some_definitions_of_ANX78xx_to_dedicated_headers.patch \
	file://armbian/0003-extract_some_Analogix_I2C_DP_common_code.patch \
	file://armbian/0004-arm64-allwinner-a64-disable-the-RTL8211E-internal-RX.patch \
	file://armbian/0004-prepare-analogix-support.patch \
	file://armbian/0004-sun4i-i2s-improvements.patch \
	file://armbian/0005-add_nalogix_anx6345_support.patch \
	file://armbian/0005-drm-gem-cma-Export-with-handle-allocator.patch \
	file://armbian/0006-add-anx6345-DP-eDP-bridge-for-Olimex-Teres-I.patch \
	file://armbian/0006-drm-sun4i-Add-GEM-allocator.patch \
	file://armbian/0007-Add-sopine-HDMI-sound-and-WiFi-support.patch \
	file://armbian/0007-anx6345_fix_acquisition_of_the_regulators.patch \
	file://armbian/0008-arm64-dts-sun50i-a64-pine64-add-HDMI-audio-nodes.patch \
	file://armbian/0009-add-a64-cyrpto.patch \
	file://armbian/0009-enable_anx6345_bridge_pinebook.patch \
	file://armbian/0010-add-mipi-dsi-pipeline.patch \
	file://armbian/0010-general-h6-add-dma-i2c-ir-spi-uart.patch \
	file://armbian/0010-media-v4l2-add_CID_UNIT_CELL_SIZE-control.patch \
	file://armbian/0011-add-thermal-sensors-a64.patch \
	file://armbian/0011-iio-adc-sun4i-gpadc-iio-rename-A33-specified-registe.patch \
	file://armbian/0011-media-v4l2-add_CTRL_TYPE_AREA-control-type.patch \
	file://armbian/0012-a64-use-macros.patch \
	file://armbian/0012-iio-adc-sun4i-gpadc-iio-rework-sampling-start-end-co.patch \
	file://armbian/0012-media-v4l2-add-definitions-for-HEVC-stateless-decoding.patch \
	file://armbian/0013-add-cpu-clocks-to-nodes.patch \
	file://armbian/0013-iio-adc-sun4i-gpadc-iio-rework-support-clocks-and-re.patch \
	file://armbian/0013-media-v4l2-add-mem2mem-support-held-capture-buffers.patch \
	file://armbian/0014-a64-enable-dvfs-and-tripping-points.patch \
	file://armbian/0014-iio-adc-sun4i-gpadc-iio-rework-support-multible-sens.patch \
	file://armbian/0014-media-v4l2-add-mem2mem-add-stateless_try_decoder_cmd-ioctl.patch \
	file://armbian/0015-add_dtsi_with_CPU_operating_points.patch \
	file://armbian/0015-iio-adc-sun4i-gpadc-iio-rework-support-nvmem-calibra.patch \
	file://armbian/0015-media-v4l2-add-mem2mem-add-new_frame-detection.patch \
	file://armbian/0016-iio-adc-sun4i-gpadc-iio-rework-add-interrupt-support.patch \
	file://armbian/0016-media-v4l2-add-V4L2_BUF_FLAG_M2M_HOLD_CAPTURE_BUF.patch \
	file://armbian/0017-iio-adc-sun4i-gpadc-iio-add-support-for-H3-thermal-s.patch \
	file://armbian/0017-media-v4l2-videodev2.h-add-V4L2_DEC_CMD_FLUSH.patch \
	file://armbian/0018-iio-adc-sun4i-gpadc-iio-add-support-for-A83T-thermal.patch \
	file://armbian/0018-media-v4l2-add-mem2mem-Fix-hold-buf-flag-checks.patch \
	file://armbian/0019-media-uapi-h264-Add-DPB-entry-field-reference-flags.patch \
	file://armbian/0020-arm-dts-sun8i-h3-add-support-for-the-thermal-sensor-.patch \
	file://armbian/0020-media-v4l2-mem2mem-mark-DONE-any-OUTPUT-queued-buffer-after-CMD_STOP-v2.patch \
	file://armbian/0021-arm-dts-sun8i-h3-add-thermal-zone-to-H3.patch \
	file://armbian/0026-iio-adc-Kconfig-enable-A80-A64-and-H5-for-THS.patch \
	file://armbian/0027-iio-adc-sun4i-gpadc-iio-add-support-for-H5-thermal-s.patch \
	file://armbian/0028-iio-adc-sun4i-gpadc-iio-add-support-for-A80-thermal-.patch \
	file://armbian/0029-iio-adc-sun4i-gpadc-iio-add-support-for-A64-thermal-.patch \
	file://armbian/0030-arm64-dts-allwinner-h5-add-support-for-the-thermal-s.patch \
	file://armbian/0031-arm64-dts-allwinner-h5-add-termal-zone-to-H5.patch \
	file://armbian/0032-arm-dts-sun9i-a80-add-support-for-the-thermal-sensor.patch \
	file://armbian/0033-arm-dts-sun9i-a80-add-thermal-zone-to-A80.patch \
	file://armbian/0035-clk-sunxi-ng-add-mux-and-pll-notifiers-for-A64-CPU-c.patch \
	file://armbian/0036-sun4i-gpadc-iio-ignore-zero-samples-to-avoid-force-p.patch \
	file://armbian/0038-ARM-dts-add-gpu-node-to-exynos4.patch \
	file://armbian/0072-drm-fourcc-add-ARM-tiled-format-modifier.patch \
	file://armbian/0074-a64-ccu-enable-LDOs-for-pll-mipi-and-add-min-max-rat.patch \
	file://armbian/0075-sopine-baseboard-enable-HS200-for-eMMC.patch \
	file://armbian/0080-rtl8723bs-disable-error-message-about-failure-to-all.patch \
	file://armbian/0101-arm64-dts-allwinner-a64-Enable-HDMI-output-on-A64-bo.patch \
	file://armbian/0103-dt-bindings-power-supply-axp20x-add-AXP803-power-bin.patch \
	file://armbian/0104-dt-bindings-gpio-gpio-axp209-add-AXP803-GPIO-binding.patch \
	file://armbian/0105-dt-bindings-iio-adc-add-AXP803-ADC-bindings.patch \
	file://armbian/0126-drm-bridge-move-ANA78xx-driver-to-analogix-subdirect.patch \
	file://armbian/0136-hdmi-audio-fixup.patch \
	file://armbian/0139-Bluetooth-Add-new-quirk-for-broken-local-ext-feature.patch \
	file://armbian/0140-Bluetooth-hci_h5-Add-support-for-reset-GPIO.patch \
	file://armbian/0141-dt-bindings-net-bluetooth-Add-rtl8723bs-bluetooth.patch \
	file://armbian/0142-Bluetooth-hci_h5-Add-support-for-binding-RTL8723BS-w.patch \
	file://armbian/0143-Bluetooth-btrtl-add-support-for-the-RTL8723CS.patch \
	file://armbian/0144-arm64-allwinner-a64-enable-Bluetooth-On-Pinebook.patch \
	file://armbian/0145-arm64-allwinner-a64-enable-Bluetooth-On-Pine64.patch \
	file://armbian/0146-arm64-allwinner-a64-enable-Bluetooth-On-SoPine-baseb.patch \
	file://armbian/0147-si2168-fix-cmd-timeout.patch \
	file://armbian/0526-pwm-sun4i-Add-support-for-Allwinner-H6.patch \
	file://armbian/0533-allwinner-h6-add-AC200-EPHY-support.patch \
	file://armbian/0534-arm64-dts-sun50i-h6-add-AC200-nodes.patch \
	file://armbian/0607-media-cedrus-choose-default-pixelformat-in-try_fmt.patch \
	file://armbian/0608-media-cedrus-fix-various-format-related-compliance-issues.patch \
	file://armbian/0609-media-cedrus-h264-Support-multiple-slices-per-frame.patch \
	file://armbian/0611-media-cedrus-Remove-unnecessary-parenthesis-aroundDIV_ROUND_UP.patch \
	file://armbian/0612-media-cedrus-Add-HEVC-decoding-support.patch \
	file://armbian/0615-media-cedrus-Fix-decoding-for-some-H264-videos.patch \
	file://armbian/0619-media-cedrus-Properly-signa-size-in-mode-register.patch \
	file://armbian/0620-media-cedrus-Fix-H264-4k-support.patch \
	file://armbian/0621-media-cedrus-Increase-maximum-supported-size.patch \
	file://armbian/0622-media-cedrus-improvements.patch \
	file://armbian/0623-media-cedrus-10bit-HEVC-hack.patch \
	file://armbian/1000-orangepi-win_enable_audio_codec.patch \
	file://armbian/2000-a64-enable-dvfs.patch \
	file://armbian/add-BergMicro-SPI-flashes.patch \
	file://armbian/Add_frame_inversion_to_correct_audio_channels.patch \
	file://armbian/add-h5-emmc-compatible.patch \
	file://armbian/add-nanopi-npi-stuff.patch \
	file://armbian/add-orangepi-zeroplus2.patch \
	file://armbian/arm64-dts-allwinner-a64-pinebook-Fix-lid-wakeup.patch \
	file://armbian/ARM-dts-sun7i-Disable-OOB-IRQ-for-brcm-wifi-on-Cubietruck-and-Banana-Pro.patch \
	file://armbian/banana-m3-remove-unstable_clocks.patch \
	file://armbian/board-a64-v3-15-19-arm64-dts-allwinner-a64-Olinuxino-enable-USB.patch \
	file://armbian/board-a64-v3-18-19-arm64-dts-allwinner-a64-NanoPi-A64-Add-Wifi-chip.patch \
	file://armbian/board-a64-v3-19-19-arm64-dts-allwinner-a64-NanoPi-A64-Add-blue-status-LED.patch \
	file://armbian/board-a83t-v7-3-4-ARM-dts-sun8i-a83t-bananapi-m3-Enable-IR-controller.patch \
	file://armbian/board-cubieboard-cubietruck-green-LED-mmc0.patch \
	file://armbian/board-cubietruck-enable-uart2.patch \
	file://armbian/board-h2plus-nanopi-duo-add-device.patch \
	file://armbian/board-h2plus-sunvell-r69-add-device.patch \
	file://armbian/board-h3-nanopi-neo-core-add-emmc.patch \
	file://armbian/board-h5-add-0000-nanopi-k1plus.patch \
	file://armbian/board-h5-add-0001-nanopi-neo-core2.patch \
	file://armbian/board-h5-add-0002-nanopi-neo2-v1.1.patch \
	file://armbian/board-h5-add-0003-nanopi-m1-plus2.patch \
	file://armbian/board-h5-orangepi-pc2-add-spi-flash.patch \
	file://armbian/board-h5-orangepi-zero-plus2-onboard-led.patch \
	file://armbian/board-h5-orangepi-zero-plus-add-regulator.patch \
	file://armbian/board-h6-add-orangepi-one-plus-and-lite2.patch_broken_below_5.1 \
	file://armbian/board-h6-orangepi-lite2-fix-missing-all.patch \
	file://armbian/board-h6-orangepioneplus-fix-missing-ethernet.patch \
	file://armbian/board-nanopi-adjust-defaults.patch \
	file://armbian/board-nanopiair-h3-camera-wifi-bluetooth-otg.patch \
	file://armbian/board-olinuxino-A64-add-eMMC.patch \
	file://armbian/board-orangepi3-add-missing-eMMC.patch \
	file://armbian/board-orangepi3-add-missing-HDMI.patch \
	file://armbian/board-orangepi3-delete-spi0.patch \
	file://armbian/board-orangepizeroplus2-missing-otg-bits.patch \
	file://armbian/board-pine64-add-spi-flash.patch \
	file://armbian/board-pine-h6-add-RTL8723.patch \
	file://armbian/board-pine-h6-pine-h6-0009-arm64-allwinner-h6-enable-MMC0-2-on-Pine-H64.patch \
	file://armbian/board-pine-h6-pine-h6-0018-arm64-allwinner-h6-enable-AXP805-PMIC-on-Pine-H64.patch \
	file://armbian/board-pine-h6-pine-h6-0019-arm64-allwinner-h6-add-PCF8563-RTC-on-Pine-H64-board.patch \
	file://armbian/board-pine-h6-pine-h6-0021-dt-bindings-usb-add-binding-for-the-DWC3-controller-.patch \
	file://armbian/board-pine-h6-pine-h6-0024-arm64-allwinner-h6-enable-USB3-port-on-Pine-H64.patch \
	file://armbian/board-pine-h6-pine-h6-0030-arm64-allwinner-h6-add-CPU-regulator-for-Pine-H64.patch \
	file://armbian/fix-a64-timejump.patch \
	file://armbian/fix-bananam2ultra-missing-clk-out-a.patch \
	file://armbian/fix-bananapi-m2-plus-wifi.patch \
	file://armbian/fix-orangepiwin-wlan0-alias.patch \
	file://armbian/fix-pinebook-backlight.patch \
	file://armbian/force-mmc0-bus-width-A64.patch \
	file://armbian/force-mmc0-bus-width-H3-H5.patch \
	file://armbian/general-add-configfs-overlay.patch \
	file://armbian/general-add-h3-mixer1.patch \
	file://armbian/general-add-H6-GPIO-disable_strict_mode.patch \
	file://armbian/general-add-i2s-DT-pins.patch \
	file://armbian/general-add-missing-uart2_rts_cts_pins-H3-H5.patch \
	file://armbian/general-add-nand-H27UBG8T2BTR.patch \
	file://armbian/general-add-overlay-compilation-support.patch \
	file://armbian/general-arm64-add-proc-cpuinfo-entries.patch \
	file://armbian/general-axp20x-sysfs-interface.patch \
	file://armbian/general-enable-kernel-dtbs-symbol-generation.patch \
	file://armbian/general-fix-builddeb-packaging.patch \
	file://armbian/general-fix-cs_gpio-spi-support.patch \
	file://armbian/general-provoke-the-early-load-of-sun8i-codec.patch \
	file://armbian/general_spi_bug_low_on_sck.patch \
	file://armbian/general-spidev-remove-warnings.patch \
	file://armbian/general-sunxi-overlays.patch \
	file://armbian/nand-disable-badblock-check-for-migration.patch \
	file://armbian/orangepi-win-fixes.patch \
	file://armbian/patch-5.4.18-19-modified.patch \
	file://armbian/patch-5.4.19-20.patch \
	file://armbian/rename_gadget_serial_console_manufacturer.patch \
	file://armbian/Revert_BT_HCIUART_RTL_ACPI_dependency.patch \
	file://armbian/sound-soc-codecs-enable-pcm5102a.patch \
	file://armbian/spi6-sck-high-too-early.patch \
	file://armbian/sunxi-h5-add-gpio-regulator-overclock.patch \
	file://armbian/timekeeping32-tweaks-for-5.0.y.patch \
	file://armbian/update-nanopi-neo-plus2-enable-regulator-fix-leds.patch \
	file://armbian/wifi-3001-add-realtek-8189es-kconfig-makefile.patch \
	file://armbian/wifi-3002-add-realtek-8189es.patch \
	file://armbian/wifi-4001-add-realtek-8723cs-kconfig-makefile.patch \
	file://armbian/wifi-4002-add-realtek-8723cs.patch \
	file://armbian/wifi-8723bs-AP-bugfix.patch \
	file://armbian/wifi-add-realtek-8189fs.patch \
	file://armbian/wifi-orangepi-pc-plus-pwrseq.patch \
	file://armbian/wifi-orangepi-prime.patch \
	file://armbian/wifi-orangepi-zero-fix-xradio-interrupt.patch \
	file://armbian/x-board-pinebook-boe-hb140wx-501-overlay.patch \
	file://armbian/xxx-add-bananapim2-zero-eth.patch \
	file://armbian/xxx-add-nanopi-r1-and-duo2.patch \
	file://armbian/xxx-add-zeropi.patch \
	file://armbian/xxx-bananapim64.patch \
	file://armbian/xxx-nanopik1plus.patch \
	file://armbian/xxx-nanopineo2v1.0-dvfs.patch \
	file://armbian/xxx-olinuxino-battery-audio.patch \
	file://armbian/xxx-orangepi2-plus-regulator.patch \
	file://armbian/xxx-orangepioneplus-enable-hdmi.patch \
	file://armbian/xxx-orangepiprime-addregulator.patch \
	file://armbian/xxx-orangepizero-plus2-default-regulator.patch \
	file://armbian/xxx-pineh64-model-a.patch \
	file://armbian/xxx-pineh64-model-b.patch \
"
